name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple jo 
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
           who-to-greet: samarth

      - name:  log time 
        run: echo "${{ steps.greet.outputs.time}}"

      
      - name: Checkout
        uses: actions/checkout@v2


